### ISSUE TITLE
Deleting last gallery item bug

### ISSUE THREAD

**Issue by Renemes** [SmileMeBack/smilemeback#32]
When deleting last gallery item (not category) then on small screen "icon view side" on the left hand side of the screen will be overlayed with the tutorial text "Tap on... icon in upper-right.." 
Solution1: to close the icon view side when deleting last gallery item. So it wont be overlayd when tutorial text is displayed.
Solution2: display the "tap on...icon" after closing "icon view side"

**Comment by tpetmanson** [comment]
fixed: Chose solution2: now the "Tap on ..." message is displayed only when in View mode.
