### ISSUE TITLE
Creating a category/gallery item

### ISSUE THREAD

**Issue by Renemes** [SmileMeBack/smilemeback#33]
1.Create a gallery or category item & finish all steps successfully but DO NOT press "Create" button 
2.Press the "back" step button (blue left side bottom screen) to go to the first step again
3. While on first step again and all steps finished press the "Back" arrow button on device (not app back button but device's hardware button). 
4.This results in creating a new category/gallery item
BUG: User wanted to discontinue creating a new item and it was force created.
Tip: Add a confirmation if user presses hardware back button on phone to make sure they really want to cancel adding a new item. Tip would say "This gallery/category item wont be created. " user then chooses:  cancel / ok

**Comment by tpetmanson** [comment]
fixed (hopefully): now displays a confirmation dialog when the user has moved between steps and has some data.

but what an unusual bug : D
Still makes me wonder why one had to go back to the first screen.
